### ISSUE TITLE
执行change_mp.py文件将模型由2块分成4块后，使用4块GPU加载分成4块的模型，报错

### ISSUE THREAD

**Issue by lulu51230** [TsinghuaAI/CPM-Finetune#17]
执行命令： CUDA_VISIBLE_DEVICES=3,4,5,7 bash scripts/finetune_chid_large_fp32.sh
时报错，排查时分别加载分成2块和4块的模型
注意：
在加载分成2块的模型时，不会报错。
在"/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/deepspeed/runtime/engine.py"这里，打印checkpoint['global_steps'] 为 **27832**

在加载分成4块的模型时，模型部分参数可以加载，
但是在"/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/deepspeed/runtime/engine.py"这里，打印checkpoint['global_steps'] 为 **None**

报以下错误，报错详情见最后一行：
[2021-02-01 12:50:26,945] [INFO] [engine.py:1284:_load_checkpoint] rank: 1 loading checkpoint: ./CPM-large_MP4/80000/mp_rank_01_model_states.pt
Traceback (most recent call last):
  File "finetune_chid.py", line 370, in <module>
    main()
  File "finetune_chid.py", line 254, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "/home/CPM-Finetune/pretrain_gpt2.py", line 186, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, lr_scheduler, args)
  File "/home/CPM-Finetune/utils.py", line 281, in load_checkpoint
    checkpoint_name, sd = model.load_checkpoint(args.load, iteration, load_module_strict=False, load_optimizer_states=False, load_lr_scheduler_states=False)
  File "/homeanaconda3/envs/pytorch/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1260, in load_checkpoint
    load_lr_scheduler_states=load_lr_scheduler_states)
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1309, in _load_checkpoint
    self.global_steps * self.train_batch_size())
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
None
checkpoint['global_steps'] 
Traceback (most recent call last):
  File "finetune_chid.py", line 370, in <module>
    main()
  File "finetune_chid.py", line 254, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "/home/CPM-Finetune/pretrain_gpt2.py", line 186, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, lr_scheduler, args)
  File "/home/CPM-Finetune/utils.py", line 281, in load_checkpoint
    checkpoint_name, sd = model.load_checkpoint(args.load, iteration, load_module_strict=False, load_optimizer_states=False, load_lr_scheduler_states=False)
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1260, in load_checkpoint
    load_lr_scheduler_states=load_lr_scheduler_states)
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1309, in _load_checkpoint
    self.global_steps * self.train_batch_size())
**TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'**

请求大佬们看看这个问题！！！

**Comment by zhenhao-huang** [comment]
好像是deepspeed问题，用的什么版本

**Comment by lulu51230** [comment]
deepspeed            0.3.10

**Comment by lulu51230** [comment]
用你们给的预训练模型，这个问题就不会出现，我自己还以为是模型切分的问题呢

**Comment by zhenhao-huang** [comment]
好像0.3.7之后的版本有改动，建议使用0.3.7,参考 #1

**Comment by lulu51230** [comment]
好的，感谢回复

**Comment by lulu51230** [comment]
已修改 deepspeed  0.3.7，但是仍然存在该问题。

**Comment by lulu51230** [comment]
我试了一下deepspeed 0.3.x，没有解决该问题，还是感觉是模型切分的问题。可是我找不到关于change_mp.py 的问题。

**Comment by lulu51230** [comment]
我查看了change_mp.py文件，model里面总共存了dict_keys(['module', 'optimizer', 'lr_scheduler', 'csr_tensor_module_names', 'skipped_steps', 'global_steps', 'global_samples', 'dp_world_size', 'mp_world_size', 'iteration', 'random_rng_state', 'np_rng_state', 'torch_rng_state', 'cuda_rng_state', 'rng_tracker_states'])
这些参数，change_mp.py仅保存了dict_keys中的'module'参数，其他都置None了。所以出现了这个问题，目前change_mp.py仅适用于generate时用。

**Comment by t1101675** [comment]
问题已经在 CPM-Generate 仓库中修复，change_mp.py 现在可以适用于 fine-tune 了。

**Comment by lulu51230** [comment]
嗯嗯，我简单修改了下，已经在跑fine-tune了，我用4张2080ti只能跑预训练模型的16层layer，并且batch设置为1。感谢您的回复。

**Comment by lichen222** [comment]
> 嗯嗯，我简单修改了下，已经在跑fine-tune了，我用4张2080ti只能跑预训练模型的16层layer，并且batch设置为1。感谢您的回复。

大佬，请问您的四张卡都是多大显存的呀～

**Comment by lulu51230** [comment]
差不多11G，不是大佬。
