### ISSUE TITLE
save_checkpoint 失败

### ISSUE THREAD

**Issue by zmingshi** [TsinghuaAI/CPM-Finetune#6]
您好：

`bash scripts/finetune_chid_large.sh`
训练过程中，保存checkpoint 的时候会失败～
其中一个进程就莫名其妙退出了，这个是什么原因呢？
软件版本：
```
torch         1.6.0+cu101
torchvision      0.7.0+cu101
deepspeed      0.3.7
```
最终保存checkpoint 信息：
```
$ll results/finetune-test-large-2021-01-06-12:09:02/dev_step-20/20
总用量 2539352
-rw-r--r-- 1 root users          0 1月   6 12:13 mp_rank_00_model_states.pt
-rw-r--r-- 1 root users 2600294812 1月   6 12:13 mp_rank_01_model_states.pt
```

详细运行日志：
```
[2021-01-06 12:08:42,968] [INFO] [config.py:648:print]   zero_optimization_stage ...... 2
[2021-01-06 12:08:42,968] [INFO] [config.py:655:print]   json = {
    "activation_checkpointing":{
        "contiguous_memory_optimization":false,
        "partition_activations":true
    },
    "fp16":{
        "enabled":true,
        "hysteresis":2,
        "loss_scale":4096,
        "loss_scale_window":1000,
        "min_loss_scale":1
    },
    "gradient_accumulation_steps":16,
    "gradient_clipping":1.0,
    "steps_per_print":100000000,
    "train_micro_batch_size_per_gpu":2,
    "wall_clock_breakdown":false,
    "zero_allow_untested_optimizer":true,
    "zero_optimization":{
        "load_from_fp32_weights":false,
        "stage":2
    }
}
[2021-01-06 12:08:42,985] [INFO] [engine.py:1348:_load_checkpoint] rank: 3 loading checkpoint: /UserData/model/cpm-model-v2/80000/mp_rank_01_model_states.pt
[2021-01-06 12:08:42,985] [INFO] [engine.py:1348:_load_checkpoint] rank: 2 loading checkpoint: /UserData/model/cpm-model-v2/80000/mp_rank_00_model_states.pt
[2021-01-06 12:08:42,985] [INFO] [engine.py:1348:_load_checkpoint] rank: 0 loading checkpoint: /UserData/model/cpm-model-v2/80000/mp_rank_00_model_states.pt
[2021-01-06 12:08:42,985] [INFO] [engine.py:1348:_load_checkpoint] rank: 1 loading checkpoint: /UserData/model/cpm-model-v2/80000/mp_rank_01_model_states.pt
[2021-01-06 12:09:01,629] [WARNING] [engine.py:1443:_get_all_zero_checkpoints] Client provided zero checkpoint load paths: ['/UserData/model/cpm-model-v2/80000/zero_pp_rank_0_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_1_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_2_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_3_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_4_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_5_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_6_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_7_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_8_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_9_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_10_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_11_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_12_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_13_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_14_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_15_mp_rank_01optim_states.pt'] does not exist
[2021-01-06 12:09:01,632] [WARNING] [engine.py:1443:_get_all_zero_checkpoints] Client provided zero checkpoint load paths: ['/UserData/model/cpm-model-v2/80000/zero_pp_rank_0_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_1_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_2_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_3_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_4_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_5_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_6_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_7_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_8_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_9_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_10_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_11_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_12_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_13_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_14_mp_rank_01optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_15_mp_rank_01optim_states.pt'] does not exist
[2021-01-06 12:09:01,776] [WARNING] [engine.py:1443:_get_all_zero_checkpoints] Client provided zero checkpoint load paths: ['/UserData/model/cpm-model-v2/80000/zero_pp_rank_0_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_1_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_2_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_3_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_4_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_5_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_6_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_7_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_8_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_9_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_10_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_11_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_12_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_13_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_14_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_15_mp_rank_00optim_states.pt'] does not exist
[2021-01-06 12:09:01,777] [WARNING] [engine.py:1443:_get_all_zero_checkpoints] Client provided zero checkpoint load paths: ['/UserData/model/cpm-model-v2/80000/zero_pp_rank_0_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_1_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_2_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_3_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_4_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_5_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_6_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_7_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_8_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_9_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_10_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_11_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_12_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_13_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_14_mp_rank_00optim_states.pt', '/UserData/model/cpm-model-v2/80000/zero_pp_rank_15_mp_rank_00optim_states.pt'] does not exist
  successfully loaded /UserData/model/cpm-model-v2/80000/mp_rank_00_model_states.pt
  successfully loaded /UserData/model/cpm-model-v2/80000/mp_rank_01_model_states.pt
  0%|                                                                                                                                      | 15/144289 [00:14<30:34:09,  1.31it/s]rank=0 time (ms) | optimizer_gradients: 180.61 | optimizer_step: 48.79 | optimizer_allgather: 603.47
  0%|                                                                                                                                      | 31/144289 [00:27<29:36:10,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 91.56 | optimizer_step: 31.31 | optimizer_allgather: 514.73
  0%|                                                                                                                                      | 47/144289 [00:40<29:37:20,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 74.44 | optimizer_step: 31.32 | optimizer_allgather: 80.74
  0%|                                                                                                                                      | 63/144289 [00:52<29:39:53,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.59 | optimizer_step: 31.32 | optimizer_allgather: 80.41
  0%|                                                                                                                                      | 79/144289 [01:04<29:40:04,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.53 | optimizer_step: 31.32 | optimizer_allgather: 81.37
  0%|                                                                                                                                      | 95/144289 [01:16<29:39:47,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.76 | optimizer_step: 31.26 | optimizer_allgather: 79.99
  0%|                                                                                                                                     | 111/144289 [01:28<29:37:57,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.38 | optimizer_step: 31.29 | optimizer_allgather: 78.60
  0%|                                                                                                                                     | 127/144289 [01:40<29:40:00,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 45.10 | optimizer_step: 31.28 | optimizer_allgather: 80.16
  0%|▏                                                                                                                                    | 143/144289 [01:52<29:44:14,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 45.24 | optimizer_step: 31.32 | optimizer_allgather: 81.51
  0%|▏                                                                                                                                    | 144/144289 [01:53<31:57:01,  1.25it/s]
Epoch 0, global step 10, total step 144289, train lm loss: 9.309432592988014
  0%|▏                                                                                                                                    | 159/144289 [02:04<29:41:58,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.26 | optimizer_step: 31.26 | optimizer_allgather: 78.85
  0%|▏                                                                                                                                    | 175/144289 [02:16<29:39:57,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 46.54 | optimizer_step: 31.28 | optimizer_allgather: 82.01
  0%|▏                                                                                                                                    | 191/144289 [02:28<29:43:42,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.24 | optimizer_step: 31.31 | optimizer_allgather: 79.31
  0%|▏                                                                                                                                    | 207/144289 [02:40<29:42:17,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 47.42 | optimizer_step: 31.29 | optimizer_allgather: 83.04
  0%|▏                                                                                                                                    | 223/144289 [02:52<29:38:44,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.50 | optimizer_step: 31.28 | optimizer_allgather: 80.95
  0%|▏                                                                                                                                    | 239/144289 [03:04<29:46:40,  1.34it/s]rank=0 time (ms) | optimizer_gradients: 44.72 | optimizer_step: 31.29 | optimizer_allgather: 79.56
  0%|▏                                                                                                                                    | 255/144289 [03:16<29:42:40,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.26 | optimizer_step: 31.26 | optimizer_allgather: 80.63
  0%|▏                                                                                                                                    | 271/144289 [03:28<29:40:01,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 50.19 | optimizer_step: 31.34 | optimizer_allgather: 80.39
  0%|▎                                                                                                                                    | 287/144289 [03:40<29:41:52,  1.35it/s]rank=0 time (ms) | optimizer_gradients: 43.51 | optimizer_step: 31.31 | optimizer_allgather: 80.84
  0%|▎                                                                                                                                    | 303/144289 [03:52<29:46:33,  1.34it/s]rank=0 time (ms) | optimizer_gradients: 43.69 | optimizer_step: 31.28 | optimizer_allgather: 81.04
  0%|▎                                                                                                                                    | 304/144289 [03:53<31:57:37,  1.25it/s]
Epoch 0, global step 20, total step 144289, train lm loss: 9.012571796774864

Epoch: 0, Global step: 20, Acc: 0.10964912176132202███████████████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:06<00:00, 11.58it/s]
[2021-01-06 12:13:04,067] [INFO] [logging.py:60:log_dist] [Rank 0] Saving model checkpoint: results/finetune-test-large-2021-01-06-12:09:02/dev_step-20/20/mp_rank_00_model_states.pt
Traceback (most recent call last):
  File "/UserData/local/miniconda3/envs/tfv1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/UserData/local/miniconda3/envs/tfv1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/UserData/local/miniconda3/envs/tfv1/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/UserData/local/miniconda3/envs/tfv1/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/UserData/local/miniconda3/envs/tfv1/bin/python', '-u', 'finetune_chid.py', '--local_rank=3', '--do_train', '--do_eval', '--data_dir', './corpus_data', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', '/UserData/model/cpm-model-v2', '--num-attention-heads', '32', '--seq-length', '1024', '--max-position-embeddings', '1024', '--tokenizer-type', 'GPT2BPETokenizer', '--fp16', '--out-seq-length', '512', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000', '--lr', '0.00001', '--warmup', '0.1', '--batch-size', '2', '--deepspeed', '--deepspeed_config', '/UserData/workspace/CPM-Finetune/scripts/ds_finetune_large.json', '--log-interval', '10', '--eval-interval', '20', '--seed', '23333', '--results_dir', 'results/', '--model_name', 'finetune-test-large', '--epoch', '1']' died with <Signals.SIGKILL: 9>.
++ pwd
```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1B:00.0 Off |                    0 |
| N/A   34C    P0    41W / 300W |     86MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1C:00.0 Off |                    0 |
| N/A   37C    P0    67W / 300W |  30539MiB / 32510MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:3D:00.0 Off |                    0 |
| N/A   38C    P0    66W / 300W |  30669MiB / 32510MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:3E:00.0 Off |                    0 |
| N/A   36C    P0    64W / 300W |  30689MiB / 32510MiB |    100%      Default |
```

剩余进程：
```
mingche+  50051 99.1 14.7 82555980 12400692 pts/13 Rl 12:06  15:19 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=1 --do_train --d
mingche+  50052  100 14.7 82658768 12369604 pts/13 Rl 12:06  15:29 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=2 --do_train --d
mingche+  50053 99.9 14.7 82673080 12391900 pts/13 Rl 12:06  15:26 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=3 --do_train --d
mingche+  50731  0.6 14.6 67648124 12319904 pts/13 Sl 12:09   0:04 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=1 --do_train --d
mingche+  50732  0.5 14.6 67666920 12314348 pts/13 Sl 12:09   0:04 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=3 --do_train --d
mingche+  50733  0.6 14.6 67644412 12291228 pts/13 Sl 12:09   0:04 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=2 --do_train --d
mingche+  50736  0.6 14.6 67666932 12315240 pts/13 Sl 12:09   0:05 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=3 --do_train --d
mingche+  50738  0.6 14.6 67648136 12319528 pts/13 Sl 12:09   0:05 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=1 --do_train --d
mingche+  50740  0.6 14.6 67644424 12293056 pts/13 Sl 12:09   0:05 /UserData/local/miniconda3/envs/tfv1/bin/python -u finetune_chid.py --local_rank=2 --do_train --d
```

**Comment by zmingshi** [comment]
内存超限制被系统kill~

**Comment by VinKK1998** [comment]
我上一次出現SIGKILL9是因为slurm管理下申请的内存小了，导致的SIGKILL，但是是在加载模型阶段退出的

**Comment by zmingshi** [comment]
> 我上一次出現SIGKILL9是因为slurm管理下申请的内存小了，导致的SIGKILL，但是是在加载模型阶段退出的

多谢哈，我这边也是因为内存问题，内存调大之后就OK了～
